# Generated by Django 4.2.4 on 2023-08-10 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pr',
            old_name='data',
            new_name='date',
        ),
        migrations.AlterField(
            model_name='workoutroutine',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
